import './globals.css';
import { Poppins } from 'next/font/google';
import ReduxProvider from '@/ReduxProvider';
import Navbar from '@/components/server/Navbar';

const poppins = Poppins({
    subsets: ['latin'],
    style: 'normal',
    weight: ['200', '400', '600'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Navbar />
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
