import './globals.css';
import type { Metadata } from 'next';
import { Exo_2 } from 'next/font/google';
import Navbar from '@/components/Navbar';
import ReduxProvider from '@/providers/ReduxProvider';

const exo2 = Exo_2({
    subsets: ['latin'],
    weight: ['100', '200', '400', '600', '800'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={exo2.className}>
                <ReduxProvider>
                    <Navbar />
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}
